version: "3.8"
services:
  oengus:
    container_name: oengus-frontend
    build:
      context: ./
      args:
        - PROFILE=production # sandbox or production-dev (for oengus.dev)
    ports:
      - "4200:80"
